sudo: false
language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
before_install:
  - gem update --system 2.1.11
  - gem --version
services:
  - rabbitmq
  - redis
env:
  - RACK_ENV=development
notifications:
  irc:
    - "irc.freenode.net#sensu"
addons:
  code_climate:
    repo_token: 0c97ad4114782ec17486d05f9fb4bc544a49f95bb231e536512ad3b324bea048